### ISSUE TITLE
To do 22/04

### ISSUE THREAD

**Issue by vSKAH** [chonorat-42/42-IRC#18]
handle PING
fix WHO
fix MSG (private)

**Comment by pgouasmi** [comment]
implement MODE

**Comment by pgouasmi** [comment]
Automatic PING OK, won’t implement /ping user

**Comment by vSKAH** [comment]
/quit [message]
    Disconnects from current server with optional leaving message.

/nick nickname
    Changes your nick.

/topic newtopic
    Changes the topic of current channel only works if you have permission to do so

/me action
    Prints "yourname action" in the current channel
